# Generated by Django 5.2.4 on 2025-07-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('shift_data', models.JSONField(default=dict)),
                ('quality_data', models.JSONField(default=dict)),
                ('checklist_data', models.JSONField(default=dict)),
                ('rolls_data', models.JSONField(default=dict)),
                ('lost_time_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brouillon de production',
                'verbose_name_plural': 'Brouillons de production',
            },
        ),
    ]
