# Generated by Django 5.2.4 on 2025-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0002_trs'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcounter',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, help_text='Date et heure du dernier reset du compteur', null=True, verbose_name='Date du dernier reset'),
        ),
    ]
