# Generated by Django 5.2.4 on 2025-07-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_migrate_production_data_to_trs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='nok_length',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='ok_length',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='raw_waste_length',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_length',
        ),
    ]
