# Generated by Django 5.2.4 on 2025-09-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_shift_nok_length_remove_shift_ok_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='preshipper_assigned',
            field=models.CharField(blank=True, help_text='Nom du pré-shipper auquel ce rouleau a été assigné (ex: S2212001)', max_length=50, null=True, verbose_name='Pré-shipper assigné'),
        ),
        migrations.AddField(
            model_name='roll',
            name='preshipper_assigned_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure d'assignation au pré-shipper", null=True, verbose_name="Date d'assignation pré-shipper"),
        ),
    ]
