# Generated by Django 5.2.4 on 2025-09-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0001_initial'),
        ('production', '0004_roll_preshipper_assigned_roll_preshipper_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_bi_autonomie_training',
            field=models.BooleanField(default=False, help_text='Type de formation: Bi Autonomie', verbose_name='Bi Autonomie'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_formation_training',
            field=models.BooleanField(default=False, help_text='Type de formation: Formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_training_shift',
            field=models.BooleanField(default=False, help_text='Indique si ce poste inclut de la formation', verbose_name='Poste de formation'),
        ),
        migrations.AddField(
            model_name='shift',
            name='trainee',
            field=models.ForeignKey(blank=True, help_text='Opérateur en formation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_shifts', to='planification.operator', verbose_name='Personne formée'),
        ),
    ]
