# Generated by Django 5.2.4 on 2025-09-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_shift_is_bi_autonomie_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_bi_autonomie_training',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_formation_training',
        ),
    ]
