# Generated by Django 5.2.4 on 2025-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Prénom de l'opérateur", max_length=50)),
                ('last_name', models.CharField(help_text="Nom de l'opérateur", max_length=50)),
                ('employee_id', models.CharField(blank=True, help_text='Matricule employé (optionnel)', max_length=20, null=True, unique=True)),
                ('training_completed', models.BooleanField(default=False, help_text='Formation terminée')),
                ('is_active', models.BooleanField(default=True, help_text='Opérateur actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opérateur',
                'verbose_name_plural': 'Opérateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
