# Generated by Django 5.2.4 on 2025-07-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text="Numéro d'ordre de fabrication saisi manuellement", max_length=50, unique=True)),
                ('required_length', models.DecimalField(decimal_places=2, help_text='Longueur totale à produire (en mètres)', max_digits=10)),
                ('target_roll_length', models.DecimalField(decimal_places=2, help_text='Longueur souhaitée par rouleau (ex: 20m)', max_digits=8)),
                ('creation_date', models.DateField(help_text="Date de création de l'OF")),
                ('planned_start_date', models.DateField(help_text='Date prévue de début')),
                ('planned_end_date', models.DateField(help_text='Date prévue de fin')),
                ('actual_start_date', models.DateField(blank=True, help_text='Date réelle de début', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='Date réelle de fin', null=True)),
                ('status', models.CharField(choices=[('created', 'Créé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordre de Fabrication',
                'verbose_name_plural': 'Ordres de Fabrication',
                'ordering': ['-creation_date', '-created_at'],
            },
        ),
    ]
