# Generated by Django 5.2.4 on 2025-07-06 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fabricationorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricationorder',
            name='actual_end_date',
        ),
        migrations.RemoveField(
            model_name='fabricationorder',
            name='actual_start_date',
        ),
        migrations.RemoveField(
            model_name='fabricationorder',
            name='planned_end_date',
        ),
        migrations.RemoveField(
            model_name='fabricationorder',
            name='planned_start_date',
        ),
        migrations.AddField(
            model_name='fabricationorder',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now().date(), help_text="Date d'échéance"),
            preserve_default=False,
        ),
    ]
