# Generated by Django 5.2.4 on 2025-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_fabricationorder_actual_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricationorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='fabricationorder',
            name='creation_date',
            field=models.DateField(auto_now_add=True, help_text="Date de création de l'OF"),
        ),
    ]
