# Generated by Django 5.2.4 on 2025-07-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fabricationorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationorder',
            name='for_cutting',
            field=models.BooleanField(default=False, help_text='Indique si cet ordre de fabrication est destiné à la découpe', verbose_name='Pour la découpe'),
        ),
    ]
