# Generated by Django 5.2.4 on 2025-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_due_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricationorder',
            name='target_roll_length',
            field=models.DecimalField(decimal_places=2, help_text='Longueur souhaitée par rouleau (ex: 20m)', max_digits=10),
        ),
    ]
