# Generated by Django 5.2.4 on 2025-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fabricationorder_target_roll_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricationorder',
            name='required_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur totale à produire (en mètres) - 0 = illimité', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fabricationorder',
            name='target_roll_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur souhaitée par rouleau (ex: 20m) - 0 = illimité', max_digits=10),
        ),
    ]
