# Generated by Django 5.2.4 on 2025-07-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_terminated_field'),
        ('core', '0008_alter_fabricationorder_required_length_and_more'),
    ]

    operations = [
    ]
