# Generated by Django 5.2.4 on 2025-07-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250706_2010'),
        ('production', '0030_change_checklist_time_to_timefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 80g/m², 40g/m²', max_length=50, unique=True, verbose_name='Nom du profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Profil par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_parameters', models.ForeignKey(blank=True, help_text='Paramètres machine associés à ce profil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='production.machineparameters', verbose_name='Paramètres machine')),
            ],
            options={
                'verbose_name': 'Profil de production',
                'verbose_name_plural': 'Profils de production',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fabricationorder',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profil définissant les paramètres et spécifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabrication_orders', to='core.profile', verbose_name='Profil de production'),
        ),
    ]
