# Generated by Django 5.2.4 on 2025-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_fabricationorder_profile'),
        ('quality', '0016_alter_specification_spec_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specifications',
            field=models.ManyToManyField(blank=True, help_text='Spécifications qualité associées à ce profil', related_name='profiles', to='quality.specification', verbose_name='Spécifications'),
        ),
    ]
