# Generated by Django 5.2.4 on 2025-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Permissif, Strict', max_length=50, unique=True, verbose_name='Nom du mode')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du mode et de ses implications', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mode par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de fonctionnement',
                'verbose_name_plural': 'Modes de fonctionnement',
                'ordering': ['name'],
            },
        ),
    ]
