# Generated by Django 5.2.4 on 2025-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Permissif, Dégradé, Maintenance', max_length=50, unique=True, verbose_name='Nom du mode')),
                ('code', models.SlugField(default='mode', help_text='Code technique du mode (ex: permissive, degraded)', unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du mode et de ses implications', verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=False, help_text='Indique si ce mode est actuellement activé', verbose_name='Activé')),
                ('is_active', models.BooleanField(default=True, help_text='Mode disponible dans le système', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode de fonctionnement',
                'verbose_name_plural': 'Modes de fonctionnement',
                'ordering': ['name'],
            },
        ),
    ]
