# Generated by Django 5.2.4 on 2025-07-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mode'),
        ('production', '0033_add_decoupe_forcee_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('no_response', 'Sans réponse'), ('happy', 'Content'), ('unhappy', 'Pas content'), ('neutral', 'Neutre')], default='no_response', help_text="Humeur déclarée par l'opérateur en fin de poste", max_length=20, verbose_name='Humeur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('shift', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mood_entry', to='production.shift', verbose_name='Poste associé')),
            ],
            options={
                'verbose_name': 'Humeur de fin de poste',
                'verbose_name_plural': 'Humeurs de fin de poste',
                'ordering': ['-created_at'],
            },
        ),
    ]
