# Generated by Django 5.2.4 on 2025-07-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(help_text='ID unique généré automatiquement (format: date_operator_vacation)', max_length=50, unique=True)),
                ('date', models.DateField(help_text='Date de production')),
                ('operator', models.CharField(help_text="Nom de l'opérateur responsable", max_length=100)),
                ('vacation', models.CharField(choices=[('Matin', 'Matin'), ('ApresMidi', 'Après-midi'), ('Nuit', 'Nuit')], help_text='Vacation du poste', max_length=20)),
                ('opening_time', models.DurationField(help_text="Temps d'ouverture du poste")),
                ('availability_time', models.DurationField(help_text='Temps de disponibilité')),
                ('lost_time', models.DurationField(help_text='Temps perdu')),
                ('operator_comments', models.TextField(blank=True, help_text="Commentaires de l'opérateur")),
                ('total_length', models.DecimalField(decimal_places=2, help_text='Longueur totale en mètres', max_digits=10)),
                ('ok_length', models.DecimalField(decimal_places=2, help_text='Longueur conforme en mètres', max_digits=10)),
                ('nok_length', models.DecimalField(decimal_places=2, help_text='Longueur non conforme en mètres', max_digits=10)),
                ('raw_waste_length', models.DecimalField(decimal_places=2, help_text='Longueur déchet brut en mètres', max_digits=10)),
                ('start_machine_parameters', models.JSONField(help_text='Paramètres machine en prise de poste')),
                ('end_machine_parameters', models.JSONField(help_text='Paramètres machine en fin de poste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
