# Generated by Django 5.2.4 on 2025-07-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='operator',
            field=models.ForeignKey(help_text='Opérateur responsable du poste', on_delete=django.db.models.deletion.CASCADE, to='core.operator'),
        ),
    ]
