# Generated by Django 5.2.4 on 2025-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_shift_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_machine_parameters',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_machine_parameters',
        ),
        migrations.AddField(
            model_name='shift',
            name='meter_reading_end',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en fin de poste (si démarrée)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='meter_reading_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en début de poste (si démarrée)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='started_at_beginning',
            field=models.BooleanField(default=False, help_text='Machine démarrée en début de poste'),
        ),
        migrations.AddField(
            model_name='shift',
            name='started_at_end',
            field=models.BooleanField(default=False, help_text='Machine démarrée en fin de poste'),
        ),
    ]
