# Generated by Django 5.2.4 on 2025-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_shift_end_machine_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='nok_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur non conforme en mètres', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='ok_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur conforme en mètres', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='raw_waste_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur déchet brut en mètres', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='total_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longueur totale en mètres', max_digits=10, null=True),
        ),
    ]
