# Generated by Django 5.2.4 on 2025-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_shift_nok_length_alter_shift_ok_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='nok_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur non conforme en mètres', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='ok_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur conforme en mètres', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='raw_waste_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur déchet brut en mètres', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='total_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longueur totale en mètres', max_digits=10),
        ),
    ]
