# Generated by Django 5.2.4 on 2025-07-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fabricationorder_status_and_more'),
        ('production', '0005_alter_shift_nok_length_alter_shift_ok_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='availability_time',
            field=models.DurationField(help_text='Temps de disponibilité', verbose_name='Temps disponible'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(help_text='Date de production', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='lost_time',
            field=models.DurationField(help_text='Temps perdu', verbose_name='Temps perdu'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='meter_reading_end',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en fin de poste (si démarrée)', max_digits=10, null=True, verbose_name='Longueur enroulée'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='meter_reading_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en début de poste (si démarrée)', max_digits=10, null=True, verbose_name='Longueur enroulée'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='opening_time',
            field=models.DurationField(help_text="Temps d'ouverture du poste", verbose_name="Temps d'ouverture"),
        ),
        migrations.AlterField(
            model_name='shift',
            name='operator',
            field=models.ForeignKey(help_text='Opérateur responsable du poste', on_delete=django.db.models.deletion.CASCADE, to='core.operator', verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='operator_comments',
            field=models.TextField(blank=True, help_text="Commentaires de l'opérateur", verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='started_at_beginning',
            field=models.BooleanField(default=False, help_text='Machine démarrée en début de poste', verbose_name='Machine démarrée'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='started_at_end',
            field=models.BooleanField(default=False, help_text='Machine démarrée en fin de poste', verbose_name='Machine démarrée'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='vacation',
            field=models.CharField(choices=[('Matin', 'Matin'), ('ApresMidi', 'Après-midi'), ('Nuit', 'Nuit')], help_text='Vacation du poste', max_length=20, verbose_name='Vacation'),
        ),
    ]
