# Generated by Django 5.2.4 on 2025-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_add_verbose_names_to_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Clé de session pour identifier la saisie', max_length=255)),
                ('form_data', models.JSONField(default=dict, help_text='Données du formulaire en JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production en cours',
                'verbose_name_plural': 'Productions en cours',
                'ordering': ['-updated_at'],
            },
        ),
    ]
