# Generated by Django 5.2.4 on 2025-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_add_current_prod_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='meter_reading_end',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en fin de poste (si démarrée)', max_digits=10, null=True, verbose_name='Lg enroulée (m)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='meter_reading_start',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrage en début de poste (si démarrée)', max_digits=10, null=True, verbose_name='Lg enroulée (m)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='operator_comments',
            field=models.TextField(blank=True, help_text="Commentaires de l'opérateur", verbose_name=''),
        ),
    ]
