# Generated by Django 5.2.4 on 2025-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_shift_meter_reading_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Heure de fin du poste', null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Heure de début du poste', null=True, verbose_name='Heure de début'),
        ),
    ]
