# Generated by Django 5.2.4 on 2025-07-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_add_start_end_time_to_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='vacation',
            field=models.CharField(choices=[('Matin', 'Matin'), ('ApresMidi', 'Après-midi'), ('Nuit', 'Nuit'), ('Journee', 'Journée')], help_text='Vacation du poste', max_length=20, verbose_name='Vacation'),
        ),
    ]
