# Generated by Django 5.2.4 on 2025-07-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250706_2010'),
        ('production', '0010_add_journee_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControlSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Clé de session pour lier au shift en cours', max_length=255)),
                ('micrometer_left_1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Gauche #1')),
                ('micrometer_left_2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Gauche #2')),
                ('micrometer_left_3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Gauche #3')),
                ('micrometer_left_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Gauche Moyenne')),
                ('micrometer_right_1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Droite #1')),
                ('micrometer_right_2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Droite #2')),
                ('micrometer_right_3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Droite #3')),
                ('micrometer_right_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Micronnaire Droite Moyenne')),
                ('dry_extract', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Extrait Sec (%)')),
                ('dry_extract_time', models.TimeField(blank=True, null=True, verbose_name='Heure Extrait Sec')),
                ('surface_mass_gg', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique GG (g/25cm²)')),
                ('surface_mass_gc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique GC (g/25cm²)')),
                ('surface_mass_left_avg', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique Gauche Moyenne')),
                ('surface_mass_dc', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique DC (g/25cm²)')),
                ('surface_mass_dd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique DD (g/25cm²)')),
                ('surface_mass_right_avg', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Masse Surfacique Droite Moyenne')),
                ('loi_given', models.BooleanField(default=False, verbose_name='LOI donnée')),
                ('loi_time', models.TimeField(blank=True, null=True, verbose_name='Heure LOI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure du contrôle')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Contrôlé par')),
                ('shift', models.ForeignKey(blank=True, help_text='Poste associé (si déjà sauvegardé)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_controls', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Série de contrôles qualité',
                'verbose_name_plural': 'Séries de contrôles qualité',
                'ordering': ['-created_at'],
            },
        ),
    ]
