# Generated by Django 5.2.4 on 2025-07-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_qualitycontrolseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycontrolseries',
            name='comments',
        ),
        migrations.AddField(
            model_name='qualitycontrolseries',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Indique si tous les contrôles sont dans les tolérances', verbose_name='Contrôles valides'),
        ),
    ]
