# Generated by Django 5.2.4 on 2025-07-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_alter_shift_availability_time_alter_shift_lost_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.CharField(help_text='ID unique du rouleau (format: OF_NumRouleau)', max_length=50, unique=True)),
                ('roll_number', models.PositiveIntegerField(verbose_name='N° Rouleau')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longueur (m)')),
                ('tube_mass', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masse tube (kg)')),
                ('total_mass', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masse totale (kg)')),
                ('is_conform', models.BooleanField(default=True, verbose_name='Conforme')),
                ('has_blocking_defects', models.BooleanField(default=False, verbose_name='Défauts bloquants')),
                ('has_thickness_issues', models.BooleanField(default=False, verbose_name="Problèmes d'épaisseur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.shift', verbose_name='Poste de production')),
            ],
            options={
                'verbose_name': 'Rouleau',
                'verbose_name_plural': 'Rouleaux',
                'ordering': ['shift', 'roll_number'],
                'unique_together': {('shift', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='RollThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_position', models.PositiveIntegerField(verbose_name='Position (mètre)')),
                ('measurement_point', models.CharField(choices=[('G1', 'Gauche 1'), ('G2', 'Gauche 2'), ('G3', 'Gauche 3'), ('D1', 'Droite 1'), ('D2', 'Droite 2'), ('D3', 'Droite 3')], max_length=2, verbose_name='Point de mesure')),
                ('thickness_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Épaisseur (mm)')),
                ('is_catchup', models.BooleanField(default=False, verbose_name='Mesure de rattrapage')),
                ('is_within_tolerance', models.BooleanField(default=True, verbose_name='Dans les tolérances')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thickness_measurements', to='production.roll', verbose_name='Rouleau')),
            ],
            options={
                'verbose_name': "Mesure d'épaisseur",
                'verbose_name_plural': "Mesures d'épaisseur",
                'ordering': ['roll', 'meter_position', 'measurement_point'],
            },
        ),
        migrations.CreateModel(
            name='RollDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=100, verbose_name='Nom du défaut')),
                ('meter_position', models.PositiveIntegerField(verbose_name='Position (mètre)')),
                ('side_position', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], max_length=10, verbose_name='Côté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='production.roll', verbose_name='Rouleau')),
            ],
            options={
                'verbose_name': 'Défaut rouleau',
                'verbose_name_plural': 'Défauts rouleaux',
                'ordering': ['roll', 'meter_position'],
                'unique_together': {('roll', 'meter_position', 'side_position', 'defect_name')},
            },
        ),
    ]
