# Generated by Django 5.2.4 on 2025-07-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250706_2010'),
        ('production', '0014_roll_rollthickness_rolldefect'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='fabrication_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='core.fabricationorder', verbose_name='Ordre de fabrication'),
        ),
    ]
