# Generated by Django 5.2.4 on 2025-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_roll_fabrication_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='is_conform',
        ),
        migrations.AddField(
            model_name='roll',
            name='destination',
            field=models.CharField(choices=[('DECOUPE', 'Découpe'), ('PRODUCTION', 'Production'), ('DECHETS', 'Déchets')], default='DECOUPE', max_length=20, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='roll',
            name='status',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], default='CONFORME', max_length=20, verbose_name='Statut'),
        ),
    ]
