# Generated by Django 5.2.4 on 2025-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_rename_qualitycontrolseries_qualitycontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollthickness',
            name='measurement_point',
            field=models.CharField(choices=[('GG', 'Gauche Gauche'), ('GC', 'Gauche Centre'), ('GD', 'Gauche Droite'), ('DG', 'Droite Gauche'), ('DC', 'Droite Centre'), ('DD', 'Droite Droite')], max_length=2, verbose_name='Point de mesure'),
        ),
    ]
