# Generated by Django 5.2.4 on 2025-07-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_add_session_key_to_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Clé de session pour lier au shift en cours', max_length=255, null=True)),
                ('motif', models.CharField(max_length=100, verbose_name="Motif d'arrêt")),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('duration', models.PositiveIntegerField(help_text="Durée de l'arrêt en minutes", verbose_name='Durée (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(blank=True, help_text='Poste associé (si déjà sauvegardé)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_time_entries', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': "Temps d'arrêt",
                'verbose_name_plural': "Temps d'arrêt",
                'ordering': ['shift', 'created_at'],
            },
        ),
    ]
