# Generated by Django 5.2.4 on 2025-07-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_losttimeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='shift_id_str',
            field=models.CharField(blank=True, help_text='ID du poste conservé même après suppression', max_length=50, null=True, verbose_name='ID du poste (texte)'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Poste associé (sera lié lors de la sauvegarde du poste)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='production.shift', verbose_name='Poste de production'),
        ),
    ]
