# Generated by Django 5.2.4 on 2025-07-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_roll_shift_id_str_alter_roll_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='losttimeentry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': "Temps d'arrêt", 'verbose_name_plural': "Temps d'arrêt"},
        ),
        migrations.AlterModelOptions(
            name='qualitycontrol',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Contrôle qualité', 'verbose_name_plural': 'Contrôles qualité'},
        ),
        migrations.AlterModelOptions(
            name='roll',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Rouleau', 'verbose_name_plural': 'Rouleaux'},
        ),
    ]
