# Generated by Django 5.2.4 on 2025-07-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250706_2010'),
        ('production', '0024_recalculate_availability_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='operator',
            field=models.ForeignKey(help_text='Opérateur responsable du poste', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Opérateur'),
        ),
    ]
