# Generated by Django 5.2.4 on 2025-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_change_operator_cascade_to_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom ou profil des paramètres machine', max_length=100, unique=True, verbose_name='Nom du profil')),
                ('oxygen_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit oxygène primaire', max_digits=6, null=True, verbose_name='Oxygène primaire')),
                ('oxygen_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit oxygène secondaire', max_digits=6, null=True, verbose_name='Oxygène secondaire')),
                ('propane_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit propane primaire', max_digits=6, null=True, verbose_name='Propane primaire')),
                ('propane_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Débit propane secondaire', max_digits=6, null=True, verbose_name='Propane secondaire')),
                ('speed_primary', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse primaire', max_digits=6, null=True, verbose_name='Vitesse primaire')),
                ('speed_secondary', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse secondaire', max_digits=6, null=True, verbose_name='Vitesse secondaire')),
                ('belt_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse du tapis en m/h', max_digits=6, null=True, verbose_name='Vitesse tapis')),
                ('is_active', models.BooleanField(default=True, help_text='Profil actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres machine',
                'verbose_name_plural': 'Paramètres machine',
                'ordering': ['name'],
            },
        ),
    ]
