# Generated by Django 5.2.4 on 2025-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_add_machine_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='avg_thickness_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Épaisseur moyenne gauche (mm)'),
        ),
        migrations.AddField(
            model_name='roll',
            name='avg_thickness_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Épaisseur moyenne droite (mm)'),
        ),
        migrations.AddField(
            model_name='roll',
            name='net_mass',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masse totale - Masse tube', max_digits=10, null=True, verbose_name='Masse nette (kg)'),
        ),
    ]
