# Generated by Django 5.2.4 on 2025-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_roll_avg_thickness_left_roll_avg_thickness_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='net_mass',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masse totale - Masse tube', max_digits=10, null=True, verbose_name='Masse nette (g)'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='total_mass',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masse totale (g)'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='tube_mass',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Masse tube (g)'),
        ),
    ]
