# Generated by Django 5.2.4 on 2025-07-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_alter_roll_net_mass_alter_roll_total_mass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='checklist_signed',
            field=models.CharField(blank=True, help_text="Initiales de l'opérateur", max_length=5, null=True, verbose_name='Signature check-list'),
        ),
        migrations.AddField(
            model_name='shift',
            name='checklist_signed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure signature check-list'),
        ),
    ]
