# Generated by Django 5.2.4 on 2025-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_change_checklist_time_to_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='comment',
            field=models.TextField(blank=True, help_text='Commentaire libre sur le rouleau', null=True, verbose_name='Commentaire'),
        ),
    ]
