# Generated by Django 5.2.4 on 2025-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_add_roll_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='avg_grammage_shift',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Moyenne des grammages de tous les rouleaux (g/m)', max_digits=6, null=True, verbose_name='Grammage moyen'),
        ),
        migrations.AddField(
            model_name='shift',
            name='avg_thickness_left_shift',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des moyennes gauches de tous les rouleaux', max_digits=5, null=True, verbose_name='Moyenne épaisseur gauche'),
        ),
        migrations.AddField(
            model_name='shift',
            name='avg_thickness_right_shift',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des moyennes droites de tous les rouleaux', max_digits=5, null=True, verbose_name='Moyenne épaisseur droite'),
        ),
    ]
