# Generated by Django 5.2.4 on 2025-07-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_shift_avg_grammage_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='destination',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('DECOUPE', 'Découpe'), ('DECOUPE_FORCEE', 'Découpe Forcée'), ('DECHETS', 'Déchets')], default='PRODUCTION', max_length=20, verbose_name='Destination'),
        ),
    ]
