# Generated by Django 5.2.4 on 2025-07-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_add_decoupe_forcee_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentProd',
        ),
    ]
