# Generated by Django 5.2.4 on 2025-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_remove_currentprod'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='grammage_calc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grammage calculé et sauvegardé (g/m)', max_digits=7, null=True, verbose_name='Grammage calculé'),
        ),
    ]
