# Generated by Django 5.2.4 on 2025-07-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0030_change_checklist_time_to_timefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de check-list',
                'verbose_name_plural': 'Templates de check-list',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name="Texte de l'item")),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wcm.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item de check-list',
                'verbose_name_plural': 'Items de check-list',
                'ordering': ['template', 'order', 'text'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('ok', 'OK'), ('na', 'N/A'), ('nok', 'NOK')], max_length=3, verbose_name='Réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcm.checklistitem', verbose_name='Item de check-list')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='production.shift', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Réponse check-list',
                'verbose_name_plural': 'Réponses check-list',
                'ordering': ['shift', 'item__order'],
                'unique_together': {('shift', 'item')},
            },
        ),
    ]
