# Generated by Django 5.2.4 on 2025-07-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mode'),
        ('production', '0031_add_roll_comment'),
        ('wcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineParametersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/heure de modification')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='Nom du paramètre')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nouvelle valeur')),
                ('parameter_type', models.CharField(choices=[('oxygen_primary', 'Oxygène primaire'), ('oxygen_secondary', 'Oxygène secondaire'), ('propane_primary', 'Propane primaire'), ('propane_secondary', 'Propane secondaire'), ('speed_primary', 'Vitesse primaire'), ('speed_secondary', 'Vitesse secondaire'), ('belt_speed', 'Vitesse bande')], max_length=50, verbose_name='Type de paramètre')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('machine_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.machineparameters', verbose_name='Paramètres machine')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator', verbose_name='Modifié par')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_parameters_history', to='production.shift', verbose_name='Poste en cours')),
            ],
            options={
                'verbose_name': 'Historique des paramètres machine',
                'verbose_name_plural': 'Historiques des paramètres machine',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='wcm_machine_timesta_a2fc11_idx'), models.Index(fields=['shift', '-timestamp'], name='wcm_machine_shift_i_156aa8_idx'), models.Index(fields=['parameter_type', '-timestamp'], name='wcm_machine_paramet_46c75f_idx')],
            },
        ),
    ]
