# Generated by Django 5.2.4 on 2025-07-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0002_machineparametershistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostTimeReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du motif')),
                ('category', models.CharField(choices=[('arret_programme', 'Arrêt programmé'), ('panne', 'Panne'), ('changement_serie', 'Changement de série'), ('reglage', 'Réglage'), ('maintenance', 'Maintenance'), ('qualite', 'Problème qualité'), ('approvisionnement', 'Approvisionnement'), ('autre', 'Autre')], max_length=30, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_planned', models.BooleanField(default=False, verbose_name='Arrêt planifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('color', models.CharField(default='#6c757d', help_text="Couleur pour l'affichage dans l'interface", max_length=7, verbose_name='Couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motif de temps perdu',
                'verbose_name_plural': 'Motifs de temps perdus',
                'ordering': ['category', 'order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='wcm_losttim_is_acti_a7717a_idx'), models.Index(fields=['code'], name='wcm_losttim_code_4dcee0_idx')],
            },
        ),
    ]
