# Generated by Django 5.2.4 on 2025-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcm', '0003_add_lost_time_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losttimereason',
            name='category',
            field=models.CharField(blank=True, choices=[('arret_programme', 'Arrêt programmé'), ('panne', 'Panne'), ('changement_serie', 'Changement de série'), ('reglage', 'Réglage'), ('maintenance', 'Maintenance'), ('qualite', 'Problème qualité'), ('approvisionnement', 'Approvisionnement'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='losttimereason',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code'),
        ),
    ]
