# Generated by Django 5.2.4 on 2025-08-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcmchecklisttemplateitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.wcmchecklistitem', verbose_name='Item'),
        ),
    ]
