# Generated by Django 5.2.4 on 2025-07-06 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du défaut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('severity', models.CharField(choices=[('non_blocking', 'Non bloquant'), ('blocking', 'Bloquant'), ('threshold', 'Bloquant selon seuil')], max_length=20, verbose_name='Criticité')),
                ('threshold_value', models.PositiveIntegerField(blank=True, help_text='Nombre maximum autorisé (pour les défauts à seuil)', null=True, verbose_name='Seuil de tolérance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de défaut',
                'verbose_name_plural': 'Types de défauts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThicknessMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.CharField(help_text='Format: OF_NumRouleau', max_length=50, verbose_name='ID Rouleau')),
                ('meter_position', models.PositiveIntegerField(verbose_name='Position (mètre)')),
                ('measurement_point', models.CharField(choices=[('G1', 'Gauche 1'), ('G2', 'Gauche 2'), ('G3', 'Gauche 3'), ('D1', 'Droite 1'), ('D2', 'Droite 2'), ('D3', 'Droite 3')], max_length=2, verbose_name='Point de mesure')),
                ('thickness_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Épaisseur (mm)')),
                ('is_within_tolerance', models.BooleanField(default=True, verbose_name='Dans les tolérances')),
                ('min_tolerance', models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Tolérance min (mm)')),
                ('max_tolerance', models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Tolérance max (mm)')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Mesuré le')),
                ('operator_comments', models.TextField(blank=True, verbose_name='Commentaires')),
            ],
            options={
                'verbose_name': "Mesure d'épaisseur",
                'verbose_name_plural': "Mesures d'épaisseur",
                'ordering': ['roll_id', 'meter_position', 'measurement_point'],
                'indexes': [models.Index(fields=['roll_id'], name='quality_thi_roll_id_ba0501_idx'), models.Index(fields=['meter_position'], name='quality_thi_meter_p_b7697f_idx'), models.Index(fields=['is_within_tolerance'], name='quality_thi_is_with_cfb4d1_idx')],
                'unique_together': {('roll_id', 'meter_position', 'measurement_point')},
            },
        ),
        migrations.CreateModel(
            name='RollDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_id', models.CharField(help_text='Format: OF_NumRouleau', max_length=50, verbose_name='ID Rouleau')),
                ('description', models.TextField(verbose_name='Description du défaut')),
                ('meter_position', models.PositiveIntegerField(verbose_name='Position (mètre)')),
                ('side_position', models.CharField(choices=[('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite')], max_length=10, verbose_name='Côté')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('blocking', 'Bloquant')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_blocking', models.BooleanField(default=False, verbose_name='Bloquant')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Détecté le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('operator_comments', models.TextField(blank=True, verbose_name='Commentaires opérateur')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.defecttype', verbose_name='Type de défaut')),
            ],
            options={
                'verbose_name': 'Défaut rouleau',
                'verbose_name_plural': 'Défauts rouleaux',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['roll_id'], name='quality_rol_roll_id_d1a768_idx'), models.Index(fields=['meter_position'], name='quality_rol_meter_p_f57787_idx'), models.Index(fields=['status'], name='quality_rol_status_e13adb_idx')],
            },
        ),
    ]
