# Generated by Django 5.2.4 on 2025-07-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_depotspecification_depotmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThicknessSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrication_order', models.CharField(max_length=50, unique=True, verbose_name='Ordre de fabrication')),
                ('ep_mini', models.DecimalField(decimal_places=2, help_text='Seuil minimum critique', max_digits=5, verbose_name='Épaisseur mini (mm)')),
                ('ep_mini_alerte', models.DecimalField(decimal_places=2, help_text="Seuil d'alerte minimum", max_digits=5, verbose_name='Épaisseur mini alerte (mm)')),
                ('ep_nominal', models.DecimalField(decimal_places=2, help_text='Valeur cible', max_digits=5, verbose_name='Épaisseur nominale (mm)')),
                ('ep_max_alerte', models.DecimalField(decimal_places=2, help_text="Seuil d'alerte maximum", max_digits=5, verbose_name='Épaisseur max alerte (mm)')),
                ('ep_maxi', models.DecimalField(decimal_places=2, help_text='Seuil maximum critique', max_digits=5, verbose_name='Épaisseur maxi (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
            ],
            options={
                'verbose_name': "Spécification d'épaisseur",
                'verbose_name_plural': "Spécifications d'épaisseur",
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['fabrication_order'], name='quality_thi_fabrica_d380bf_idx'), models.Index(fields=['is_active'], name='quality_thi_is_acti_97d2a1_idx')],
            },
        ),
        migrations.DeleteModel(
            name='DepotMeasurement',
        ),
        migrations.DeleteModel(
            name='DepotSpecification',
        ),
    ]
