# Generated by Django 5.2.4 on 2025-07-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_thicknessspecification_delete_depotmeasurement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thicknessspecification',
            old_name='ep_nominal',
            new_name='ep_nominale',
        ),
        migrations.RemoveField(
            model_name='thicknessspecification',
            name='ep_maxi',
        ),
    ]
