# Generated by Django 5.2.4 on 2025-07-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_auto_20250707_0017'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='thicknessspecification',
            name='quality_thi_fabrica_d380bf_idx',
        ),
        migrations.RemoveField(
            model_name='thicknessspecification',
            name='fabrication_order',
        ),
        migrations.AlterField(
            model_name='thicknessspecification',
            name='ep_nominale',
            field=models.DecimalField(decimal_places=2, help_text='Valeur cible standard', max_digits=5, verbose_name='Épaisseur nominale (mm)'),
        ),
    ]
