# Generated by Django 5.2.4 on 2025-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_remove_thicknessspecification_quality_thi_fabrica_d380bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thicknessspecification',
            name='max_nok',
            field=models.PositiveIntegerField(default=4, help_text="Nombre maximum d'épaisseurs NOK sur un rouleau", verbose_name='Max NOK'),
        ),
    ]
