# Generated by Django 5.2.4 on 2025-07-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_add_is_blocking_to_thicknessspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('thickness', 'Épaisseur'), ('micrometer', 'Micrionnaire'), ('surface_mass', 'Masse surfacique'), ('dry_extract', 'Extrait sec')], max_length=20, verbose_name='Type')),
                ('name', models.CharField(help_text='Ex: 80gr/m², 40gr/m²', max_length=50, verbose_name='Nom')),
                ('value_min', models.DecimalField(blank=True, decimal_places=3, help_text='Seuil minimum critique', max_digits=10, null=True, verbose_name='Valeur minimale')),
                ('value_min_alert', models.DecimalField(blank=True, decimal_places=3, help_text="Seuil d'alerte minimum", max_digits=10, null=True, verbose_name='Valeur minimale alerte')),
                ('value_nominal', models.DecimalField(blank=True, decimal_places=3, help_text='Valeur cible standard', max_digits=10, null=True, verbose_name='Valeur nominale')),
                ('value_max_alert', models.DecimalField(blank=True, decimal_places=3, help_text="Seuil d'alerte maximum", max_digits=10, null=True, verbose_name='Valeur maximale alerte')),
                ('value_max', models.DecimalField(blank=True, decimal_places=3, help_text='Seuil maximum critique', max_digits=10, null=True, verbose_name='Valeur maximale')),
                ('unit', models.CharField(blank=True, help_text='Ex: mm, %, g/m²', max_length=10, verbose_name='Unité')),
                ('max_nok', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de mesures NOK autorisées', null=True, verbose_name='Max NOK')),
                ('is_blocking', models.BooleanField(default=True, help_text='Le non-respect de cette spec rend le produit non conforme', verbose_name='Bloquant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
            ],
            options={
                'verbose_name': 'Spécification',
                'verbose_name_plural': 'Spécifications',
                'ordering': ['spec_type', 'name'],
                'indexes': [models.Index(fields=['spec_type', 'is_active'], name='quality_spe_spec_ty_a0cf82_idx')],
                'unique_together': {('spec_type', 'name')},
            },
        ),
    ]
