# Generated by Django 5.2.4 on 2025-07-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_increase_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_type',
            field=models.CharField(choices=[('thickness', 'Épaisseur'), ('micrometer', 'Micronnaire'), ('surface_mass', 'Masse surfacique'), ('dry_extract', 'Extrait sec')], max_length=20, verbose_name='Type'),
        ),
    ]
