# Generated by Django 5.2.4 on 2025-07-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_alter_specification_spec_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolldefect',
            name='defect_type',
        ),
        migrations.DeleteModel(
            name='ThicknessMeasurement',
        ),
        migrations.DeleteModel(
            name='RollDefect',
        ),
    ]
