# Generated by Django 5.2.4 on 2025-07-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_remove_obsolete_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_type',
            field=models.CharField(choices=[('thickness', 'Épaisseur'), ('micrometer', 'Micronnaire'), ('surface_mass', 'Masse surfacique'), ('dry_extract', 'Extrait sec'), ('global_surface_mass', 'Masse surfacique globale')], max_length=20, verbose_name='Type'),
        ),
    ]
