# Generated by Django 5.2.4 on 2025-07-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0015_alter_specification_spec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_type',
            field=models.CharField(choices=[('thickness', 'Épaisseur'), ('micrometer', 'Micronnaire'), ('surface_mass', 'Masse surfacique (g/25cm²)'), ('dry_extract', 'Extrait sec'), ('global_surface_mass', 'Masse surfacique globale (g/m²)')], max_length=20, verbose_name='Type'),
        ),
    ]
