# Generated by Django 5.2.4 on 2025-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('roll_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brouillon de rouleau',
                'verbose_name_plural': 'Brouillons de rouleaux',
                'db_table': 'livesession_live_roll',
                'indexes': [models.Index(fields=['session_key', 'is_active'], name='livesession_session_c17a58_idx')],
                'unique_together': {('session_key', 'is_active')},
            },
        ),
    ]
