# Generated by Django 5.2.4 on 2025-07-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0002_liveroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentproductionstate',
            name='active_productivity_tab',
            field=models.CharField(choices=[('temps', 'TRS'), ('parametres', 'Params & Specs')], default='temps', max_length=20, verbose_name='Onglet actif productivité'),
        ),
    ]
