# Generated by Django 5.2.4 on 2025-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0003_currentproductionstate_active_productivity_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentproductionstate',
            name='roll_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de rouleau actuel'),
        ),
    ]
