# Generated by Django 5.2.4 on 2025-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0004_currentproductionstate_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('quality_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brouillon contrôles qualité',
                'verbose_name_plural': 'Brouillons contrôles qualité',
                'db_table': 'livesession_live_quality',
            },
        ),
    ]
