# Generated by Django 5.2.4 on 2025-07-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0005_livequalitycontrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveShift',
            new_name='CurrentSession',
        ),
        migrations.RenameField(
            model_name='currentsession',
            old_name='shift_data',
            new_name='session_data',
        ),
        migrations.AlterModelOptions(
            name='currentsession',
            options={
                'verbose_name': 'Session de production',
                'verbose_name_plural': 'Sessions de production'
            },
        ),
        migrations.AlterModelTable(
            name='currentsession',
            table='livesession_currentsession',
        ),
    ]