# Generated by Django 5.2.4 on 2025-07-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0006_rename_liveshift_to_currentsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveRoll',
        ),
    ]
