# Generated by Django 5.2.4 on 2025-07-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0007_remove_liveroll_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentProductionState',
        ),
        migrations.DeleteModel(
            name='LiveQualityControl',
        ),
    ]